name: CoffeeBeans
favicon: null
layout_spectrum: 0.98578
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5625
  lightness: 0.7076833830215037
  saturation: 0.41381172463297844
  rhythmicContrast: 0.6213800185360014
purpose: []
